name: Create new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
      branch:
        description: 'Branch'
        required: true
        type: string
        default: 'master'

jobs:
  deploy:
    name: Deploy new version
    runs-on: ubuntu-latest
    env:
      CI: ''
      GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: checkout
        uses: actions/checkout@v3

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: git config
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          git config --global user.email "cypherGUI-bot@github.com"
          git config --global user.name "cypherGUI-bot"
          git remote set-url origin https://git:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          
          git checkout -b release-${{ inputs.version }}
          npm version ${{ inputs.version }} --allow-same-version
          git push origin release-${{ inputs.version }}
          git tag -d $(git tag -l)
          
          gh pr create --title "Release ${{ inputs.version }}" -B ${{ inputs.branch }} -H release-${{ inputs.version }} --fill
          gh pr merge release-${{ inputs.version }} --delete-branch --merge
          gh release create ${{ inputs.version }} --generate-notes
