name: Playwright e2e tests on Neo4j

on:
  pull_request:
    branches: [master]

jobs:
  playwright-neo4j:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.43.0-jammy

    services:
      neo4j:
        image: neo4j:latest
        env:
          NEO4J_AUTH: neo4j/nothing123
#          NEO4J_PLUGINS: '["apoc"]'
        ports:
          - 7687:7687
          - 7474:7474
        options: >-
          --health-cmd "wget http://localhost:7474 || exit 1"

    steps:
      - name: Get movies dataset
        run: |
          wget -O movies.cypher https://raw.githubusercontent.com/neo4j-graph-examples/movies/main/scripts/movies.cypher
          cypher-shell -u "neo4j" -p "nothing123" "MATCH (n) DETACH DELETE n"
          cypher-shell -u "neo4j" -p "nothing123" -f movies.cypher

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm ci

#      - name: Install Playwright Browsers
#        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npm run playwright
#        env:
#          URL: 'ws://thingsdb:9270'