name: Playwright e2e tests

on:
  pull_request:
    branches: [master]

jobs:
  neo4j-read-only:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.43.0-jammy

    services:
      neo4j:
        image: neo4j:latest
        env:
          NEO4J_AUTH: neo4j/nothing123
        #          NEO4J_PLUGINS: '["apoc"]'
        ports:
          - 7687:7687
          - 7474:7474
        options: >-
          --health-cmd "wget http://localhost:7474 || exit 1"

    steps:
      - name: Get movies dataset
        run: |
          wget -O movies.cypher https://raw.githubusercontent.com/neo4j-graph-examples/movies/main/scripts/movies.cypher
          cypher-shell -u "neo4j" -p "nothing123" "MATCH (n) DETACH DELETE n"
          cypher-shell -u "neo4j" -p "nothing123" -f movies.cypher
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: npm ci
      #      - name: Install Playwright Browsers
      #        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests (read-only)
        run: npm run playwright:read-only
        env:
          DB_USERNAME: 'neo4j'
          DB_PASSWORD: 'nothing123'

      - name: Build
        run: npm run build
      - name: Run Playwright tests (build)
        run: npm run playwright:build
        env:
          DB_USERNAME: 'neo4j'
          DB_PASSWORD: 'nothing123'

  neo4j-read-write:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.43.0-jammy

    services:
      neo4j:
        image: neo4j:latest
        env:
          NEO4J_AUTH: neo4j/nothing123
        #          NEO4J_PLUGINS: '["apoc"]'
        ports:
          - 7687:7687
          - 7474:7474
        options: >-
          --health-cmd "wget http://localhost:7474 || exit 1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: npm ci
      #      - name: Install Playwright Browsers
      #        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests (read-write)
        run: npm run playwright:read-write
        env:
          DB_USERNAME: 'neo4j'
          DB_PASSWORD: 'nothing123'

  neo4j-multidatabase:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.43.0-jammy

    services:
      neo4j:
        image: neo4j:enterprise
        env:
          NEO4J_AUTH: neo4j/nothing123
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
        #          NEO4J_PLUGINS: '["apoc"]'
        ports:
          - 7687:7687
          - 7474:7474
        options: >-
          --health-cmd "wget http://localhost:7474 || exit 1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests (multidatabase)
        run: npm run playwright:multidatabase
        env:
          DB_USERNAME: 'neo4j'
          DB_PASSWORD: 'nothing123'

  memgraph:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.43.0-jammy

    services:
      memgraph:
        image: memgraph/memgraph:latest
        ports:
          - 7687:7687
        # not tested
        options: >-
          --health-cmd "echo 'RETURN 0;' | mgconsole || exit 1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests (memgraph)
        run: npm run playwright:memgraph
